parameters:
  fluentd:
    agent:
      plugin:
        fluent-plugin-prometheus:
          gem: ['fluent-plugin-prometheus']
      config:
        input:
          prometheus:
            metric:
              type: prometheus
