classes:
- system.prometheus.alertmanager.container
parameters:
  docker:
    client:
      stack:
        monitoring:
          network:
            monitoring:
              driver: overlay
              driver_opts:
                encrypted: 1
          service:
            alertmanager:
              networks:
                - monitoring
              deploy:
                replicas: 2
                labels:
                  com.mirantis.monitoring: "alertmanager"
                restart_policy:
                  condition: any
              labels:
                com.mirantis.monitoring: "alertmanager"
              image: ${_param:docker_image_alertmanager}
              ports:
                - 15011:${prometheus:alertmanager:bind:port}
              volumes:
                - ${prometheus:alertmanager:dir:config}:${_param:prometheus_alertmanager_config_directory}
                - ${prometheus:alertmanager:dir:data}:${_param:prometheus_alertmanager_data_directory}
              environment:
                ALERTMANAGER_CONFIG_DIR: ${_param:prometheus_alertmanager_config_directory}
                ALERTMANAGER_DATA_DIR: ${_param:prometheus_alertmanager_data_directory}
                ALERTMANAGER_BIND_PORT: ${prometheus:alertmanager:bind:port}
                ALERTMANAGER_BIND_ADDRESS: ${prometheus:alertmanager:bind:address}
                ALERTMANAGER_DISCOVERY_DOMAIN: 'monitoring_alertmanager'
                ALERTMANAGER_EXTERNAL_URL: "http://${_param:stacklight_monitor_address}:15011"
