classes:
- system.docker.swarm.stack.monitoring.prometheus
- system.docker.swarm.stack.monitoring.prometheus.replicated
- system.docker.swarm.stack.monitoring.alertmanager
- system.docker.swarm.stack.monitoring.prometheus_relay
- system.docker.swarm.stack.monitoring.pushgateway
- system.docker.swarm.stack.monitoring.remote_agent
- system.docker.swarm.stack.monitoring.remote_storage_adapter
