classes:
- system.prometheus.pushgateway.container
parameters:
  docker:
    client:
      stack:
        monitoring:
          network:
            monitoring:
              driver: overlay
              driver_opts:
                encrypted: 1
          service:
            pushgateway:
              networks:
                - monitoring
              deploy:
                replicas: 2
                labels:
                  com.mirantis.monitoring: "pushgateway"
                restart_policy:
                  condition: any
              environment:
                PUSHGATEWAY_BIND_PORT: ${prometheus:pushgateway:bind:port}
                PUSHGATEWAY_BIND_ADDRESS: ${prometheus:pushgateway:bind:address}
              labels:
                com.mirantis.monitoring: "pushgateway"
              image: ${_param:docker_image_pushgateway}
              ports:
                - 15012:${prometheus:pushgateway:bind:port}
